apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssp-nodejs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ssp-nodejs
    spec:
      containers:
      - name: ssp-nodejs
        image: ssp25/ssp-nodejs-proj:master6
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
